print_info() {
  prin "OS" "$(uname)"
  info "Kernel" kernel
  info "Terminal" term
  info "CPU" cpu
  info "GPU" gpu
  info "Memory" memory
  info "Uptime" uptime
}

# Kernel

kernel_shorthand="on"

# Uptime

uptime_shorthand="on"

# Memory

memory_percent="off"

memory_unit="mib"

# CPU

speed_type="bios_limit"

speed_shorthand="off"

cpu_brand="on"

cpu_speed="off"

cpu_cores="logical"

cpu_temp="off"

# GPU

gpu_brand="off"

gpu_type="all"

refresh_rate="off"

# Text Colors

colors=(7 7 7 7 7 7)

# Text Options

bold="on"

underline_enabled="on"

underline_char=" "

separator=":"

# Backend Settings

image_backend="ascii"

# Image Source

image_source="${HOME}/.config/neofetch/cat.txt"

ascii_bold="on"

# Image Options

image_loop="off"

# Thumbnail directory

thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
